server:
  port: 8080
spring:
  application:
    name: llm-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chatbot?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 200483
  redis:
    port: 6379
    host: localhost
    database: 3
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.sztu: debug
sztu:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: kunar
    # 设置jwt过期时间
    admin-ttl: 720000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
xfxh:
  # 服务引擎使用 讯飞星火认知大模型V2.0，如果使用 V1.5 需要将 hostUrl 修改为 https://spark-api.xf-yun.com/v1.1/chat
  hostUrl: https://spark-api.xf-yun.com/v3.5/chat
  # 发送请求时指定的访问领域，如果是 V1.5版本 设置为 general，如果是 V2版本 设置为 generalv2
  domain: generalv3.5
  # 核采样阈值。用于决定结果随机性，取值越高随机性越强即相同的问题得到的不同答案的可能性越高。取值 [0,1]
  temperature: 0.5
  # 模型回答的tokens的最大长度，V1.5取值为[1,4096]，V2.0取值为[1,8192]。
  maxTokens: 2048
  # 大模型回复问题的最大响应时长，单位 s
  maxResponseTime: 30
  # 允许同时连接大模型的 websocket 数，如果是普通（免费）用户为 2，超过这个数连接响应会报错，具体参考官网。
  QPS: 2
  # 用于权限验证，从服务接口认证信息中获取
  appId: af013b90
  # 用于权限验证，从服务接口认证信息中获取
  apiKey: 892f952515c86ae3599348950f86271a
  # 用于权限验证，从服务接口认证信息中获取
  apiSecret: MjE1MGM3N2IyYmM3NGYzMDZjYjRhZjk4
